# RaceMind

## Objective

Build an interactive Formula 1 strategy simulator using FastF1 race data to analyze tire degradation, pit-stop strategies, and race outcomes.

In [2]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [7]:
import fastf1
import pandas as pd

fastf1.Cache.enable_cache('../data')

In [8]:
session = fastf1.get_session(2025, 'Abu Dhabi', 'R')
session.load()

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

In [9]:
session.drivers

['1',
 '81',
 '4',
 '16',
 '63',
 '14',
 '31',
 '44',
 '27',
 '18',
 '5',
 '87',
 '55',
 '22',
 '12',
 '23',
 '6',
 '30',
 '10',
 '43']

In [10]:
session.results[['Abbreviation', 'FullName', 'TeamName', 'Position']]

   Abbreviation           FullName         TeamName  Position
1           VER     Max Verstappen  Red Bull Racing       1.0
81          PIA      Oscar Piastri          McLaren       2.0
4           NOR       Lando Norris          McLaren       3.0
16          LEC    Charles Leclerc          Ferrari       4.0
63          RUS     George Russell         Mercedes       5.0
14          ALO    Fernando Alonso     Aston Martin       6.0
31          OCO       Esteban Ocon     Haas F1 Team       7.0
44          HAM     Lewis Hamilton          Ferrari       8.0
27          HUL    Nico Hulkenberg      Kick Sauber       9.0
18          STR       Lance Stroll     Aston Martin      10.0
5           BOR  Gabriel Bortoleto      Kick Sauber      11.0
87          BEA     Oliver Bearman     Haas F1 Team      12.0
55          SAI       Carlos Sainz         Williams      13.0
22          TSU       Yuki Tsunoda  Red Bull Racing      14.0
12          ANT     Kimi Antonelli         Mercedes      15.0
23          ALB    Alexander Albon         Williams      16.0
6           HAD       Isack Hadjar     Racing Bulls      17.0
30          LAW        Liam Lawson     Racing Bulls      18.0
10          GAS       Pierre Gasly           Alpine      19.0
43          COL   Franco Colapinto           Alpine      20.0

In [11]:
laps = session.laps

laps[['Driver', 'LapNumber', 'LapTime', 'Compound']].head()

  Driver  LapNumber                LapTime Compound
0    VER        1.0 0 days 00:01:31.677000   MEDIUM
1    VER        2.0 0 days 00:01:29.117000   MEDIUM
2    VER        3.0 0 days 00:01:29.555000   MEDIUM
3    VER        4.0 0 days 00:01:29.563000   MEDIUM
4    VER        5.0 0 days 00:01:29.695000   MEDIUM

In [12]:
ver_laps = laps.pick_drivers('VER')

ver_laps[['LapNumber', 'LapTime', 'Compound']].head(20)

    LapNumber                LapTime Compound
0         1.0 0 days 00:01:31.677000   MEDIUM
1         2.0 0 days 00:01:29.117000   MEDIUM
2         3.0 0 days 00:01:29.555000   MEDIUM
3         4.0 0 days 00:01:29.563000   MEDIUM
4         5.0 0 days 00:01:29.695000   MEDIUM
5         6.0 0 days 00:01:29.772000   MEDIUM
6         7.0 0 days 00:01:29.744000   MEDIUM
7         8.0 0 days 00:01:29.601000   MEDIUM
8         9.0 0 days 00:01:29.413000   MEDIUM
9        10.0 0 days 00:01:29.465000   MEDIUM
10       11.0 0 days 00:01:29.538000   MEDIUM
11       12.0 0 days 00:01:29.543000   MEDIUM
12       13.0 0 days 00:01:29.633000   MEDIUM
13       14.0 0 days 00:01:29.526000   MEDIUM
14       15.0 0 days 00:01:29.703000   MEDIUM
15       16.0 0 days 00:01:29.460000   MEDIUM
16       17.0 0 days 00:01:29.578000   MEDIUM
17       18.0 0 days 00:01:29.596000   MEDIUM
18       19.0 0 days 00:01:29.614000   MEDIUM
19       20.0 0 days 00:01:29.557000   MEDIUM

In [13]:
print(laps.columns.tolist())

['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

In [14]:
laps[['Driver', 'LapNumber', 'LapTime', 'Compound', 'TyreLife']].head()

  Driver  LapNumber                LapTime Compound  TyreLife
0    VER        1.0 0 days 00:01:31.677000   MEDIUM       1.0
1    VER        2.0 0 days 00:01:29.117000   MEDIUM       2.0
2    VER        3.0 0 days 00:01:29.555000   MEDIUM       3.0
3    VER        4.0 0 days 00:01:29.563000   MEDIUM       4.0
4    VER        5.0 0 days 00:01:29.695000   MEDIUM       5.0

In [15]:
ver_laps = laps.pick_drivers('VER')

ver_laps[['LapNumber', 'Compound', 'TyreLife', 'LapTime']].head(30)

    LapNumber Compound  TyreLife                LapTime
0         1.0   MEDIUM       1.0 0 days 00:01:31.677000
1         2.0   MEDIUM       2.0 0 days 00:01:29.117000
2         3.0   MEDIUM       3.0 0 days 00:01:29.555000
3         4.0   MEDIUM       4.0 0 days 00:01:29.563000
4         5.0   MEDIUM       5.0 0 days 00:01:29.695000
5         6.0   MEDIUM       6.0 0 days 00:01:29.772000
6         7.0   MEDIUM       7.0 0 days 00:01:29.744000
7         8.0   MEDIUM       8.0 0 days 00:01:29.601000
8         9.0   MEDIUM       9.0 0 days 00:01:29.413000
9        10.0   MEDIUM      10.0 0 days 00:01:29.465000
10       11.0   MEDIUM      11.0 0 days 00:01:29.538000
11       12.0   MEDIUM      12.0 0 days 00:01:29.543000
12       13.0   MEDIUM      13.0 0 days 00:01:29.633000
13       14.0   MEDIUM      14.0 0 days 00:01:29.526000
14       15.0   MEDIUM      15.0 0 days 00:01:29.703000
15       16.0   MEDIUM      16.0 0 days 00:01:29.460000
16       17.0   MEDIUM      17.0 0 days 00:01:29.578000
17       18.0   MEDIUM      18.0 0 days 00:01:29.596000
18       19.0   MEDIUM      19.0 0 days 00:01:29.614000
19       20.0   MEDIUM      20.0 0 days 00:01:29.557000
20       21.0   MEDIUM      21.0 0 days 00:01:29.441000
21       22.0   MEDIUM      22.0 0 days 00:01:29.243000
22       23.0   MEDIUM      23.0 0 days 00:01:31.365000
23       24.0     HARD       1.0 0 days 00:01:48.923000
24       25.0     HARD       2.0 0 days 00:01:28.693000
25       26.0     HARD       3.0 0 days 00:01:28.312000
26       27.0     HARD       4.0 0 days 00:01:28.327000
27       28.0     HARD       5.0 0 days 00:01:28.371000
28       29.0     HARD       6.0 0 days 00:01:28.003000
29       30.0     HARD       7.0 0 days 00:01:28.049000

In [16]:
ver_medium = ver_laps[ver_laps['Compound'] == 'MEDIUM']

ver_medium[['TyreLife', 'LapTime']].head(20)

    TyreLife                LapTime
0        1.0 0 days 00:01:31.677000
1        2.0 0 days 00:01:29.117000
2        3.0 0 days 00:01:29.555000
3        4.0 0 days 00:01:29.563000
4        5.0 0 days 00:01:29.695000
5        6.0 0 days 00:01:29.772000
6        7.0 0 days 00:01:29.744000
7        8.0 0 days 00:01:29.601000
8        9.0 0 days 00:01:29.413000
9       10.0 0 days 00:01:29.465000
10      11.0 0 days 00:01:29.538000
11      12.0 0 days 00:01:29.543000
12      13.0 0 days 00:01:29.633000
13      14.0 0 days 00:01:29.526000
14      15.0 0 days 00:01:29.703000
15      16.0 0 days 00:01:29.460000
16      17.0 0 days 00:01:29.578000
17      18.0 0 days 00:01:29.596000
18      19.0 0 days 00:01:29.614000
19      20.0 0 days 00:01:29.557000

In [17]:
ver_medium[['TyreLife', 'LapTime']].tail(20)

    TyreLife                LapTime
3        4.0 0 days 00:01:29.563000
4        5.0 0 days 00:01:29.695000
5        6.0 0 days 00:01:29.772000
6        7.0 0 days 00:01:29.744000
7        8.0 0 days 00:01:29.601000
8        9.0 0 days 00:01:29.413000
9       10.0 0 days 00:01:29.465000
10      11.0 0 days 00:01:29.538000
11      12.0 0 days 00:01:29.543000
12      13.0 0 days 00:01:29.633000
13      14.0 0 days 00:01:29.526000
14      15.0 0 days 00:01:29.703000
15      16.0 0 days 00:01:29.460000
16      17.0 0 days 00:01:29.578000
17      18.0 0 days 00:01:29.596000
18      19.0 0 days 00:01:29.614000
19      20.0 0 days 00:01:29.557000
20      21.0 0 days 00:01:29.441000
21      22.0 0 days 00:01:29.243000
22      23.0 0 days 00:01:31.365000

In [18]:
ver_laps['Compound'].unique()

array(['MEDIUM', 'HARD'], dtype=object)

In [19]:
ver_medium[['TyreLife', 'LapTime']]

    TyreLife                LapTime
0        1.0 0 days 00:01:31.677000
1        2.0 0 days 00:01:29.117000
2        3.0 0 days 00:01:29.555000
3        4.0 0 days 00:01:29.563000
4        5.0 0 days 00:01:29.695000
5        6.0 0 days 00:01:29.772000
6        7.0 0 days 00:01:29.744000
7        8.0 0 days 00:01:29.601000
8        9.0 0 days 00:01:29.413000
9       10.0 0 days 00:01:29.465000
10      11.0 0 days 00:01:29.538000
11      12.0 0 days 00:01:29.543000
12      13.0 0 days 00:01:29.633000
13      14.0 0 days 00:01:29.526000
14      15.0 0 days 00:01:29.703000
15      16.0 0 days 00:01:29.460000
16      17.0 0 days 00:01:29.578000
17      18.0 0 days 00:01:29.596000
18      19.0 0 days 00:01:29.614000
19      20.0 0 days 00:01:29.557000
20      21.0 0 days 00:01:29.441000
21      22.0 0 days 00:01:29.243000
22      23.0 0 days 00:01:31.365000

In [35]:
ver_laps[['LapNumber', 'Compound', 'TyreLife', 'Stint']]

    LapNumber Compound  TyreLife  Stint
0         1.0   MEDIUM       1.0    1.0
1         2.0   MEDIUM       2.0    1.0
2         3.0   MEDIUM       3.0    1.0
3         4.0   MEDIUM       4.0    1.0
4         5.0   MEDIUM       5.0    1.0
5         6.0   MEDIUM       6.0    1.0
6         7.0   MEDIUM       7.0    1.0
7         8.0   MEDIUM       8.0    1.0
8         9.0   MEDIUM       9.0    1.0
9        10.0   MEDIUM      10.0    1.0
10       11.0   MEDIUM      11.0    1.0
11       12.0   MEDIUM      12.0    1.0
12       13.0   MEDIUM      13.0    1.0
13       14.0   MEDIUM      14.0    1.0
14       15.0   MEDIUM      15.0    1.0
15       16.0   MEDIUM      16.0    1.0
16       17.0   MEDIUM      17.0    1.0
17       18.0   MEDIUM      18.0    1.0
18       19.0   MEDIUM      19.0    1.0
19       20.0   MEDIUM      20.0    1.0
20       21.0   MEDIUM      21.0    1.0
21       22.0   MEDIUM      22.0    1.0
22       23.0   MEDIUM      23.0    1.0
23       24.0     HARD       1.0    2.0
24       25.0     HARD       2.0    2.0
25       26.0     HARD       3.0    2.0
26       27.0     HARD       4.0    2.0
27       28.0     HARD       5.0    2.0
28       29.0     HARD       6.0    2.0
29       30.0     HARD       7.0    2.0
30       31.0     HARD       8.0    2.0
31       32.0     HARD       9.0    2.0
32       33.0     HARD      10.0    2.0
33       34.0     HARD      11.0    2.0
34       35.0     HARD      12.0    2.0
35       36.0     HARD      13.0    2.0
36       37.0     HARD      14.0    2.0
37       38.0     HARD      15.0    2.0
38       39.0     HARD      16.0    2.0
39       40.0     HARD      17.0    2.0
40       41.0     HARD      18.0    2.0
41       42.0     HARD      19.0    2.0
42       43.0     HARD      20.0    2.0
43       44.0     HARD      21.0    2.0
44       45.0     HARD      22.0    2.0
45       46.0     HARD      23.0    2.0
46       47.0     HARD      24.0    2.0
47       48.0     HARD      25.0    2.0
48       49.0     HARD      26.0    2.0
49       50.0     HARD      27.0    2.0
50       51.0     HARD      28.0    2.0
51       52.0     HARD      29.0    2.0
52       53.0     HARD      30.0    2.0
53       54.0     HARD      31.0    2.0
54       55.0     HARD      32.0    2.0
55       56.0     HARD      33.0    2.0
56       57.0     HARD      34.0    2.0
57       58.0     HARD      35.0    2.0

In [38]:
ver_clean = ver_laps.pick_quicklaps()

ver_clean['LapTimeSeconds'] = ver_clean['LapTime'].dt.total_seconds()

ver_clean[['LapNumber', 'Compound', 'TyreLife', 'LapTimeSeconds']].head()

C:\Users\OJAS\AppData\Local\Temp\ipykernel_31008\2939305981.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ver_clean['LapTimeSeconds'] = ver_clean['LapTime'].dt.total_seconds()

   LapNumber Compound  TyreLife  LapTimeSeconds
0        1.0   MEDIUM       1.0          91.677
1        2.0   MEDIUM       2.0          89.117
2        3.0   MEDIUM       3.0          89.555
3        4.0   MEDIUM       4.0          89.563
4        5.0   MEDIUM       5.0          89.695

In [41]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (2.1.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: six>=1.5 in c:\Users\OJAS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)
Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.5 MB 6.0 MB/s eta 0:00:02
   ------------ --------------------------- 2.9/9.5 MB 6.8 MB/s eta 0:00:01
   ---------------- ----------------------- 3.9/9.5 MB 6.1 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.5 MB 6.1 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.5 MB 6.0 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 5.3 MB/s  0:00:02
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels

   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   ---------------------------------------- 2/2 [statsmodels]

Successfully installed patsy-1.0.2 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import plotly.express as px

fig = px.scatter(
    ver_clean,
    x='TyreLife',
    y='LapTimeSeconds',
    color='Compound',
    title='Max Verstappen: Tyre Life vs Lap Time'
)

fig.show()

In [43]:
fig = px.line(
    ver_clean,
    x='TyreLife',
    y='LapTimeSeconds',
    color='Compound',
    title='Max Verstappen Tyre Degradation'
)

fig.show()

## Insight 1: Tyre Behaviour

Verstappen's Medium tyres showed minimal degradation across a 23-lap stint, maintaining a consistent pace around 89.4–89.8 seconds.

The Hard tyres exhibited a typical lifecycle pattern: an initial warm-up period, a stable performance window, and gradual degradation beyond approximately 28 laps of tyre life.

In [3]:
from src.degradation import prepare_lap_times

In [20]:
ver_clean = prepare_lap_times(ver_laps)

ver_clean[['LapNumber', 'Compound', 'TyreLife', 'LapTimeSeconds']].head()

   LapNumber Compound  TyreLife  LapTimeSeconds
0        1.0   MEDIUM       1.0          91.677
1        2.0   MEDIUM       2.0          89.117
2        3.0   MEDIUM       3.0          89.555
3        4.0   MEDIUM       4.0          89.563
4        5.0   MEDIUM       5.0          89.695

In [27]:
import importlib
import src.degradation

importlib.reload(src.degradation)

In [23]:
from src.degradation import get_degradation_score

In [24]:
score = get_degradation_score(ver_laps)

print(score)

-0.024954677265775212

In [28]:
from src.degradation import get_stint_summary

In [29]:
get_stint_summary(ver_laps)

   Stint Compound  Laps  AveragePace
0      1   MEDIUM    23       89.713
1      2     HARD    34       88.093

In [30]:
import plotly.express as px

fig = px.bar(
    get_stint_summary(ver_laps),
    x='Stint',
    y='AveragePace',
    color='Compound',
    title='Verstappen Average Pace by Stint'
)

fig.show()

## Insight 2: Strategy Overview

Verstappen executed a one-stop strategy in Abu Dhabi 2025.

The Medium compound was used for the opening 23 laps, followed by a switch to Hard tyres for the remainder of the race.

The Hard stint delivered a faster average pace (88.093s) compared to the Medium stint (89.713s), benefiting from lower fuel loads and stable tyre performance.

In [31]:
import importlib
import src.degradation

importlib.reload(src.degradation)

from src.degradation import get_driver_strategy_summary

In [32]:
grid_summary = get_driver_strategy_summary(laps)

grid_summary.head(20)

    Stint Compound  Laps  AveragePace Driver
0       1   MEDIUM    23       89.713    VER
1       2     HARD    34       88.093    VER
2       1     HARD    40       89.495    PIA
3       2   MEDIUM    16       87.438    PIA
4       1   MEDIUM    15       89.889    NOR
5       2     HARD    23       88.552    NOR
6       3     HARD    17       87.439    NOR
7       1   MEDIUM    15       90.001    LEC
8       2     HARD    22       88.758    LEC
9       3   MEDIUM    18       87.502    LEC
10      1   MEDIUM    13       90.179    RUS
11      2     HARD    43       89.274    RUS
12      1   MEDIUM    15       90.279    ALO
13      2     HARD    41       89.625    ALO
14      1   MEDIUM    18       90.728    OCO
15      2     HARD    38       89.405    OCO
16      1     SOFT     7       90.731    HAM
17      2     HARD    22       89.879    HAM
18      3   MEDIUM    26       88.889    HAM
19      1     SOFT     6       90.984    HUL

In [33]:
avg_pace = (
    grid_summary
    .groupby('Driver')['AveragePace']
    .mean()
    .sort_values()
    .reset_index()
)

In [34]:
fig = px.bar(
    avg_pace.head(10),
    x='Driver',
    y='AveragePace',
    title='Top 10 Drivers by Average Race Pace'
)

fig.show()

In [35]:
medium_stints = grid_summary[
    grid_summary['Compound'] == 'MEDIUM'
]

medium_stints.sort_values(
    'AveragePace'
).head(10)

    Stint Compound  Laps  AveragePace Driver
3       2   MEDIUM    16       87.438    PIA
9       3   MEDIUM    18       87.502    LEC
21      3   MEDIUM    15       88.088    HUL
23      2   MEDIUM    15       88.181    STR
43      3   MEDIUM    16       88.502    GAS
46      3   MEDIUM    16       88.547    COL
18      3   MEDIUM    26       88.889    HAM
36      3   MEDIUM    24       88.905    ALB
33      2   MEDIUM    25       88.926    ANT
31      2   MEDIUM    25       89.214    TSU

In [36]:
hard_stints = grid_summary[
    grid_summary['Compound'] == 'HARD'
]

hard_stints.sort_values(
    'AveragePace'
).head(10)

    Stint Compound  Laps  AveragePace Driver
6       3     HARD    17       87.439    NOR
1       2     HARD    34       88.093    VER
5       2     HARD    23       88.552    NOR
8       2     HARD    22       88.758    LEC
11      2     HARD    43       89.274    RUS
15      2     HARD    38       89.405    OCO
2       1     HARD    40       89.495    PIA
40      2     HARD    35       89.527    LAW
29      2     HARD    39       89.617    SAI
13      2     HARD    41       89.625    ALO

In [39]:
hard_stints.sort_values(
    'AveragePace'
).head(20)

    Stint Compound  Laps  AveragePace Driver
6       3     HARD    17       87.439    NOR
1       2     HARD    34       88.093    VER
5       2     HARD    23       88.552    NOR
8       2     HARD    22       88.758    LEC
11      2     HARD    43       89.274    RUS
15      2     HARD    38       89.405    OCO
2       1     HARD    40       89.495    PIA
40      2     HARD    35       89.527    LAW
29      2     HARD    39       89.617    SAI
13      2     HARD    41       89.625    ALO
27      2     HARD    43       89.644    BEA
17      2     HARD    22       89.879    HAM
25      2     HARD    42       89.947    BOR
42      2     HARD    26       90.048    GAS
20      2     HARD    34       90.072    HUL
38      2     HARD    42       90.087    HAD
45      2     HARD    24       90.182    COL
35      2     HARD    24       90.222    ALB
22      1     HARD    41       90.492    STR
30      1     HARD    31       90.590    TSU

In [40]:
hard_driver_avg = (
    hard_stints
    .groupby('Driver')['AveragePace']
    .mean()
    .sort_values()
    .reset_index()
)

In [41]:
fig = px.bar(
    hard_driver_avg.head(10),
    x='Driver',
    y='AveragePace',
    title='Top Drivers on Hard Tyres'
)

fig.show()

## Insight 3: Hard Tyre Performance Comparison

Comparing average pace across Hard tyre stints highlights differences in tyre management and long-run performance between drivers.

Rather than focusing on race position, this analysis evaluates how effectively each driver maintained pace while running the Hard compound over extended stints.

Drivers with lower average lap times demonstrated stronger pace retention and more efficient tyre usage during the race.

In [42]:
from src.strategy import get_actual_strategy

In [43]:
get_actual_strategy(ver_laps)

   Stint Compound  Laps  AveragePace
0      1   MEDIUM    23       89.713
1      2     HARD    34       88.093

In [44]:
get_actual_strategy(ver_laps)

   Stint Compound  Laps  AveragePace
0      1   MEDIUM    23       89.713
1      2     HARD    34       88.093

In [45]:
def get_pit_lap(driver_laps):

    summary = get_stint_summary(driver_laps)

    first_stint_laps = summary.iloc[0]["Laps"]

    return int(first_stint_laps)

In [46]:
get_pit_lap(ver_laps)

23

In [49]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [50]:
from src.strategy import estimate_race_time

In [52]:
import importlib
import src.strategy

print(src.strategy.__file__)

importlib.reload(src.strategy)

print(dir(src.strategy))

d:\projects\Racemind\src\strategy.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'estimate_race_time', 'get_actual_strategy', 'get_pit_lap', 'get_stint_summary', 'prepare_lap_times']

In [53]:
from src.strategy import get_pit_lap

In [54]:
print(get_actual_strategy(ver_laps))

{'NumberOfStints': 2, 'Compounds': ['MEDIUM', 'HARD'], 'LapsPerStint': [23, 34]}

In [55]:
print(get_pit_lap(ver_laps))

23

In [56]:
print(estimate_race_time(ver_laps))

5058.546

In [57]:
print(get_actual_strategy(ver_laps))
print(get_pit_lap(ver_laps))
print(round(estimate_race_time(ver_laps), 2))

{'NumberOfStints': 2, 'Compounds': ['MEDIUM', 'HARD'], 'LapsPerStint': [23, 34]}
23
5058.55

In [58]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [59]:
from src.strategy import simulate_pit_stop

In [60]:
simulate_pit_stop(
    ver_laps,
    pit_lap=20
)

{'ActualPitLap': 23,
 'SimulatedPitLap': 20,
 'ActualRaceTime': np.float64(5058.55),
 'SimulatedRaceTime': np.float64(5058.1),
 'Difference': np.float64(0.45)}

In [61]:
results = []

for lap in range(18, 29):

    simulation = simulate_pit_stop(
        ver_laps,
        pit_lap=lap
    )

    results.append(simulation)

In [62]:
import pandas as pd

simulation_df = pd.DataFrame(results)

simulation_df

,ActualPitLap,SimulatedPitLap,ActualRaceTime,SimulatedRaceTime,Difference
0,23,18,5058.55,5057.80,0.75
1,23,19,5058.55,5057.95,0.60
2,23,20,5058.55,5058.10,0.45
3,23,21,5058.55,5058.25,0.30
4,23,22,5058.55,5058.40,0.15
5,23,23,5058.55,5058.55,0.00
6,23,24,5058.55,5058.70,-0.15
7,23,25,5058.55,5058.85,-0.30
8,23,26,5058.55,5059.00,-0.45
9,23,27,5058.55,5059.15,-0.60
10,23,28,5058.55,5059.30,-0.75

## Insight 4: Pit Stop Simulation Prototype

A prototype strategy simulator was developed to evaluate alternative pit-stop windows.

Using the actual race strategy as a baseline, the simulator estimates race-time changes resulting from earlier or later pit stops.

The current implementation uses a simplified time-gain model and serves as the foundation for future data-driven strategy simulations.

In [63]:
import plotly.express as px

fig = px.line(
    simulation_df,
    x="SimulatedPitLap",
    y="SimulatedRaceTime",
    markers=True,
    title="Verstappen Pit Stop Simulation"
)

fig.show()

In [64]:
import importlib
import src.degradation

importlib.reload(src.degradation)

In [65]:
from src.degradation import get_compound_pace

In [66]:
get_compound_pace(ver_laps)

  Compound  LapTimeSeconds
0     HARD       88.092559
1   MEDIUM       89.713000

In [68]:
import importlib
import src.degradation

importlib.reload(src.degradation)

In [69]:
from src.degradation import get_compound_degradation

In [70]:
get_compound_degradation(
    ver_laps,
    "MEDIUM"
)

{'Compound': 'MEDIUM',
 'Slope': np.float64(-0.005114624505930317),
 'Intercept': np.float64(89.77437549407115)}

In [71]:
get_compound_degradation(
    ver_laps,
    "HARD"
)

{'Compound': 'HARD',
 'Slope': np.float64(0.008646753246753463),
 'Intercept': np.float64(87.93259388846442)}

In [72]:
medium = prepare_lap_times(ver_laps)
medium = medium[
    medium["Compound"] == "MEDIUM"
]

fig = px.scatter(
    medium,
    x="TyreLife",
    y="LapTimeSeconds",
    trendline="ols",
    title="Medium Tyre Degradation Model"
)

fig.show()

In [73]:
hard = prepare_lap_times(ver_laps)
hard = hard[
    hard["Compound"] == "HARD"
]

fig = px.scatter(
    hard,
    x="TyreLife",
    y="LapTimeSeconds",
    trendline="ols",
    title="Hard Tyre Degradation Model"
)

fig.show()

In [74]:
hard_model = get_compound_degradation(
    ver_laps,
    "HARD"
)

hard_model

{'Compound': 'HARD',
 'Slope': np.float64(0.008646753246753463),
 'Intercept': np.float64(87.93259388846442)}

In [76]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [77]:
from src.strategy import predict_hard_lap_time

In [78]:
hard_model = get_compound_degradation(
    ver_laps,
    "HARD"
)

hard_model

{'Compound': 'HARD',
 'Slope': np.float64(0.008646753246753463),
 'Intercept': np.float64(87.93259388846442)}

In [79]:
predict_hard_lap_time(
    tyre_life=10,
    intercept=hard_model["Intercept"],
    slope=hard_model["Slope"]
)

np.float64(88.01906142093196)

In [80]:
predict_hard_lap_time(
    tyre_life=30,
    intercept=hard_model["Intercept"],
    slope=hard_model["Slope"]
)

np.float64(88.19199648586702)

In [81]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [82]:
from src.strategy import predict_hard_stint_time

In [83]:
predict_hard_stint_time(
    laps=34,
    intercept=hard_model["Intercept"],
    slope=hard_model["Slope"]
)

np.float64(2994.8530103896087)

In [84]:
predicted_hard_time = predict_hard_stint_time(
    laps=34,
    intercept=hard_model["Intercept"],
    slope=hard_model["Slope"]
)

predicted_hard_time

np.float64(2994.8530103896087)

In [85]:
hard_laps = prepare_lap_times(ver_laps)

hard_laps = hard_laps[
    hard_laps["Compound"] == "HARD"
]

actual_hard_time = (
    hard_laps["LapTimeSeconds"]
    .sum()
)

actual_hard_time

np.float64(2995.147)

In [86]:
difference = (
    predicted_hard_time
    - actual_hard_time
)

difference

np.float64(-0.29398961039123606)

In [87]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [88]:
from src.strategy import predict_strategy_time

In [90]:
medium_model = get_compound_degradation(
    ver_laps,
    "MEDIUM"
)

hard_model = get_compound_degradation(
    ver_laps,
    "HARD"
)

In [91]:

medium_model
hard_model

{'Compound': 'HARD',
 'Slope': np.float64(0.008646753246753463),
 'Intercept': np.float64(87.93259388846442)}

In [92]:
predict_strategy_time(
    medium_laps=23,
    hard_laps=34,
    medium_intercept=medium_model["Intercept"],
    medium_slope=medium_model["Slope"],
    hard_intercept=hard_model["Intercept"],
    hard_slope=hard_model["Slope"]
)

np.float64(5058.252010389609)

In [93]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [94]:
from src.strategy import simulate_strategy_window

In [95]:
simulation_results = simulate_strategy_window(
    18,
    28,
    medium_model,
    hard_model
)

In [96]:
simulation_df = pd.DataFrame(
    simulation_results
)

simulation_df

    PitLap  PredictedRaceTime
0       18        5051.179787
1       19        5052.587168
2       20        5053.998080
3       21        5055.412525
4       22        5056.830502
5       23        5058.252010
6       24        5059.677051
7       25        5061.105625
8       26        5062.537730
9       27        5063.973367
10      28        5065.412537

In [97]:
import plotly.express as px

fig = px.line(
    simulation_df,
    x="PitLap",
    y="PredictedRaceTime",
    markers=True,
    title="Pit Stop Window Simulation"
)

fig.show()

## Insight 5: Strategy Window Analysis

A degradation-driven strategy simulator was developed using tyre performance models derived from race telemetry.

The simulation evaluated multiple pit-stop windows and estimated the resulting race time for each strategy.

For Verstappen's Abu Dhabi 2025 race, the model suggests that earlier pit stops produce lower overall race times, while delaying the stop progressively increases the predicted race duration.

In [99]:
import importlib
import src.strategy

importlib.reload(src.strategy)

In [100]:
from src.strategy import find_optimal_pit_stop

In [101]:
best_strategy = find_optimal_pit_stop(
    simulation_df
)

best_strategy

PitLap                 18.000000
PredictedRaceTime    5051.179787
Name: 0, dtype: float64

## Limitation

The current tyre degradation model does not explicitly account for fuel load reduction and track evolution throughout the race. As a result, compound pace comparisons may not reflect the intrinsic performance difference between tyre compounds.

In [2]:
import sys
from pathlib import Path

sys.path.append(
    str(Path().resolve().parent)
)

In [3]:
from src.data_loader import (
    load_race_session,
    get_driver_laps
)

In [4]:
session = load_race_session()

ver_laps = get_driver_laps(
    session,
    "VER"
)

ver_laps.head()

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) C:\Users\OJAS\AppData\Local\Temp\fastf1
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:59:52.411000,VER,1,0 days 00:01:31.677000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.489000,...,True,Red Bull Racing,0 days 00:58:20.522000,2025-12-07 13:03:27.585,1,1.0,False,,False,False
1,0 days 01:01:21.528000,VER,1,0 days 00:01:29.117000,2.0,1.0,NaT,NaT,0 days 00:00:18.085000,0 days 00:00:38.383000,...,True,Red Bull Racing,0 days 00:59:52.411000,2025-12-07 13:04:59.474,1,1.0,False,,False,True
2,0 days 01:02:51.083000,VER,1,0 days 00:01:29.555000,3.0,1.0,NaT,NaT,0 days 00:00:18.197000,0 days 00:00:38.495000,...,True,Red Bull Racing,0 days 01:01:21.528000,2025-12-07 13:06:28.591,1,1.0,False,,False,True
3,0 days 01:04:20.646000,VER,1,0 days 00:01:29.563000,4.0,1.0,NaT,NaT,0 days 00:00:18.253000,0 days 00:00:38.441000,...,True,Red Bull Racing,0 days 01:02:51.083000,2025-12-07 13:07:58.146,1,1.0,False,,False,True
4,0 days 01:05:50.341000,VER,1,0 days 00:01:29.695000,5.0,1.0,NaT,NaT,0 days 00:00:18.142000,0 days 00:00:38.529000,...,True,Red Bull Racing,0 days 01:04:20.646000,2025-12-07 13:09:27.709,1,1.0,False,,False,True

In [5]:
nor_laps = get_driver_laps(
    session,
    "NOR"
)

len(ver_laps), len(nor_laps)

(58, 58)

In [7]:
from src.degradation import (
    get_compound_degradation
)

In [8]:
ver_medium = get_compound_degradation(
    ver_laps,
    "MEDIUM"
)

ver_hard = get_compound_degradation(
    ver_laps,
    "HARD"
)

nor_medium = get_compound_degradation(
    nor_laps,
    "MEDIUM"
)

nor_hard = get_compound_degradation(
    nor_laps,
    "HARD"
)

print(ver_medium)
print(ver_hard)

print()

print(nor_medium)
print(nor_hard)

{'Compound': 'MEDIUM', 'Slope': np.float64(-0.005114624505930317), 'Intercept': np.float64(89.77437549407115)}
{'Compound': 'HARD', 'Slope': np.float64(0.008646753246753463), 'Intercept': np.float64(87.93259388846442)}

{'Compound': 'MEDIUM', 'Slope': np.float64(0.041821428571428336), 'Intercept': np.float64(89.51307380952379)}
{'Compound': 'HARD', 'Slope': np.float64(0.00046854225036988646), 'Intercept': np.float64(88.07355634211439)}